version: '3'
services:
    yasmine-frontend:
        build: frontend
        image: yasmine/frontend
        container_name: yasmine-frontend
        volumes:
            - ./:/code
        ports:
            - "1841:1841"   
        links:
            - yasmine-backend
    yasmine-backend:
        ports:
            - "80:80"
        build: backend
        image: yasmine/backend
        container_name: yasmine-backend
        stdin_open: true
        tty: true        
        volumes:
            - yasmine:/opt/yasmine
            - ./backend:/opt/yasmine/src               
volumes:
  yasmine:
